# Site settings
title: Profundo Bono
description: "A non-profit theater company of Delaware lawyers and legal professionals"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://profundobono.com" # the name of your domain
logo: img/logo.jpg

# Hero
hero: 
    hero_img: header1-1.png
    hero_title: Profundo Bono

# Contact form
api_token: # Enter API token here
    
# Social settings
social:
  links:
    - https://www.facebook.com/ProfundoBono/
facebook:
  publisher: https://www.facebook.com/ProfundoBono/
#instagram: http://instagram.com
youtube: https://www.youtube.com/channel/UCPFa51xPuziGkjQtjWuWKhA
#skype: skype:obaez_design?userinfo
#feed: yes

# Footer
copyright: Profundo Bono - All rights reserved - Website by <a href="https://www.catloafsoft.com/" target="_new">Catloaf Software, LLC</a>

sass:
  sass_dir: _scss

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore,
    svg
]

# Theme Settings
google_tag: GTM-NRZD38Z
google_verification:
