# Site settings
title: Peninsula Symphonic Winds
description: "A community concert band based in Torrance and Palos Verdes, California"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pswinds.org" # the name of your domain
logo: /svg/min/logo.svg

# Hero
hero: 
    hero_img: header1-1.png
    hero_title: Profundo Bono

# Contact form
api_token: # Enter API token here
    
# Social settings
social:
  links:
    - https://www.facebook.com/ProfundoBono/
facebook:
  publisher: https://www.facebook.com/ProfundoBono/
#instagram: http://instagram.com
youtube: https://www.youtube.com/channel/UCPFa51xPuziGkjQtjWuWKhA
#skype: skype:obaez_design?userinfo
#feed: yes

# Footer
copyright: Profundo Bono - All rights reserved

sass:
  sass_dir: _scss

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore,
    svg
]

# Theme Settings
analytics: 
google_verification: GyLoky4K_7PDHveeLuvncOM83dNwdGrbBeknxgtP_bE
